# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Enable yarn workspace
      - name: Enable yarn workspace
        run: yarn config set workspaces-experimental true

      # Runs a single command using the runners shell
      - name: Install packages
        run: yarn

      # Compile typescript packages
      - name: Compile packages
        run: yarn workspaces run tsc

      # Build android app
      - name: Build Android Release
        run: |
          yarn && cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed."

      - name: Send file app-release.apk to discord channel
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: android/app/build/outputs/apk/release/app-release.apk
